job "microservices-app-localVM" {
  # Nomad dev mode uses "dc1" datacenter by default
  datacenters = ["dc1"]
  
  type = "service"

  # Backend service group
  group "backend" {
    # Single instance for local development
    count = 1

    # Network configuration
    network {
      #mode = "bridge"
      
      port "http" {
        # Use static port for easier access
        static = 3000
        to     = 3000
      }
    }
  
    # Backend task
    task "backend" {
      driver = "docker"

       # Register service with Nomad native service discovery
      service {
        provider = "nomad"
        name = "backend-api"
        port = "http"
        

        # Service metadata
        meta {
          version     = "1.0.0"
          environment = "development"
        }

        # Health check
        check {
          type     = "http"
          path     = "/health"
          interval = "10s"
          timeout  = "2s"
          
          check_restart {
            limit           = 3
            grace           = "10s"
            ignore_warnings = false
          }
        }
      }

      config {
        image = "aimeeu/microservices-backend:latest"
        ports = ["http"]
        
        # For local development, you can use locally built images
        # To use local image instead of Docker Hub:
        # 1. Build: docker build -t microservices-backend:latest ./backend
        # 2. Change image to: image = "microservices-backend:latest"
        # 3. Set: force_pull = false
        
        force_pull = false
      }

      # Environment variables
      env {
        PORT     = "3000"
        NODE_ENV = "development"
      }

      # Resource allocation - lighter for local VM
      resources {
        cpu    = 500  # MHz
        memory = 256  # MB
      }

      # Logging
      logs {
        max_files     = 5
        max_file_size = 10
      }
    }

    # Restart policy
    restart {
      attempts = 2
      delay    = "15s"
      interval = "5m"
      mode     = "fail"
    }
  }

  # Frontend service group
  group "frontend" {
    # Single instance for local development
    count = 1

    # Network configuration
    network {
      #mode = "bridge"
      
      port "http" {
        # Use static port for easier access
        static = 8080
        to     = 80
      }
    }    

    # Frontend task
    task "frontend" {
      driver = "docker"

      # Register service with Nomad native service discovery
      service {
        provider = "nomad"
        name = "frontend-web"
        port = "http"


        # Service metadata
        meta {
          version     = "1.0.0"
          environment = "development"
        }

        # Health check
        check {
          type     = "http"
          path     = "/health"
          interval = "10s"
          timeout  = "2s"
          
          check_restart {
            limit           = 3
            grace           = "10s"
            ignore_warnings = false
          }
        }
      }

      config {
        image = "aimeeu/microservices-frontend:latest"
        ports = ["http"]
        
        # For local development with local image:
        # 1. Build: docker build -t microservices-frontend:latest ./frontend
        # 2. Change image to: image = "microservices-frontend:latest"
        # 3. Set: force_pull = false
        
        force_pull = false
      }

      # Template to generate config.js with backend API URL from Nomad service discovery
      template {
        data = <<EOH
// Backend API Configuration
// Generated by Nomad template at runtime
window.APP_CONFIG = {
{{- range nomadService "backend-api" }}
    BACKEND_API_URL: 'http://{{ .Address }}:{{ .Port }}'
{{- end }}
{{- if not (nomadService "backend-api") }}
    BACKEND_API_URL: 'http://localhost:3000'
{{- end }}
};
EOH
        destination = "local/config.js"
        change_mode = "restart"
      }

      # Environment variables
      env {
        NODE_ENV = "development"
      }

      # Resource allocation - lighter for local VM
      resources {
        cpu    = 300  # MHz
        memory = 128  # MB
      }

      # Logging
      logs {
        max_files     = 5
        max_file_size = 10
      }
    }

    # Restart policy
    restart {
      attempts = 2
      delay    = "15s"
      interval = "5m"
      mode     = "fail"
    }
  }
}